---
title: "powerlifting_time_series"
author: "Charlie Pepin-Woods"
date: "2025-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(zoo)   # For time series manipulation
library(stats)  # For AR model fitting
library(TSA)    # For time series analysis
library(ggplot2)  # For visualization
library(TTR)
```


```{r}
df <- read.csv("openpowerlifting_interpolated.csv")
head(df)
```

We will take the first lifter, A J Vasquez as an example to show the plots

```{r}
aj <- df[df$Name == "A J Vasquez", ]
head(aj)
```



```{r}
totals <- aj[, c("Time", "TotalKg")]
```

```{r}
ggplot(totals, aes(x = Time, y = TotalKg)) +
  geom_line() +
  ggtitle('Totals over Time') +
  xlab('Time') +
  ylab('Totals') +
  theme_minimal()
```

```{r}
decomp1 <- decompose(ts(totals$TotalKg, frequency = 25), type = "additive")
plot(decomp1)
```

```{r}
for (i in 1:4) {
  totals[, paste0('Lag_', i)] <- c(rep(NA, i), head(totals$TotalKg, -i))
}

totals <- na.omit(totals)

acf(totals$TotalKg)
```

```{r}
train_size <- round(0.8 * nrow(totals))
train_data <- totals[1:train_size,]
test_data <- totals[(train_size + 1):nrow(totals),]

y_train <- train_data$TotalKg
y_test <- test_data$TotalKg
```

```{r}
head(train_data)
```

```{r}
X_train <- diff(train_data$Lag_1)

# Fit AR(1) Model (OLS)
# X_matrix <- as.matrix(cbind(1, X_train))  # Add intercept column (if desired)
X_matrix <- matrix(X_train, ncol=1)
y_vector <- matrix(y_train[-1], ncol=1)
w <- solve(t(X_matrix) %*% X_matrix) %*% (t(X_matrix) %*% y_vector)
w

# Predict Total using AR(1)
y_pred <- numeric(length(y_test))
start <- tail(X_train, 1)
start

for (i in 1:length(y_test)) {
  # y_pred[i] <- as.numeric(w[1] + w[2] * start) # if using intercept
  y_pred[i] <- as.numeric(w*start)
  start <- y_pred[i]
}

y_pred

final_predictions <- y_pred + tail(y_train, 1)
```

```{r}
y_test
```


```{r}
# Observed vs predicted plot
plot(final_predictions, y_test, ylab = "Observed Totals", xlab = "Predicted Totals", main = "AR(1) Model Predictions")
abline(0, 1, col = "red")

# Time series plot of actual vs predicted SO9
plot(test_data$Time, test_data$TotalKg, type = "l", col = "blue", lwd = 2, ylim = range(c(y_pred, test_data$TotalKg)), xlab = "Time", ylab = "Total", main = "AR(1) Model Predictions")
lines(test_data$Time, y_pred, col = "red", lwd = 2, lty = 2)
legend("topleft", legend = c("Actual Total", "AR(1) Predicted Total"), col = c("blue", "red"), lty = c(1, 2), bty = "n")
```

```{r}
X_train <- train_data[c("Lag_1", "Lag_2", "Lag_3", "Lag_4")]

# Scatterplot to confirm correlation at Lag 1
# plot(X_train, y_train, xlab = "Lag 4 Total", ylab = "Observed Total", main = "Lag 4 vs Total")

# Fit AR(4) Model (OLS)
# X_matrix <- as.matrix(cbind(1, X_train))  # Add intercept column (if desired)
X_matrix <- as.matrix(X_train, ncol=4)
y_vector <- matrix(y_train, ncol=1)
w <- solve(t(X_matrix) %*% X_matrix) %*% (t(X_matrix) %*% y_vector)
w <- as.matrix(w, ncol=1)

# Predict Total using AR(4)
y_pred <- numeric(length(y_test))
start <- tail(X_train, 4)

start <- as.matrix(start, ncol=1)
start <- t(start)

for (i in 1:length(y_test)) {
  # y_pred[i] <- as.numeric(w[1] + w[2] * start) # if using intercept
  y_pred[i] <- as.numeric(t(w) %*% start)
  y_pred[i]
  start <- rbind(start, y_pred[i])
  start <- start[-1,]
  start <- as.matrix(start, ncol=1)
}

final_predictions <- y_pred + tail(y_train, 1)
```

```{r}
# Observed vs predicted plot
plot(final_predictions, y_test, ylab = "Observed Totals", xlab = "Predicted Totals", main = "AR(4) Model Predictions")
abline(0, 1, col = "red")

# Time series plot of actual vs predicted Totals
plot(test_data$Time, test_data$TotalKg, type = "l", col = "blue", lwd = 2, ylim = range(c(y_pred, test_data$TotalKg)), xlab = "Time", ylab = "Total", main = "AR(4) Model Predictions")
lines(test_data$Time, final_predictions, col = "red", lwd = 2, lty = 2)
legend("topleft", legend = c("Actual Total", "AR(4) Predicted Total"), col = c("blue", "red"), lty = c(1, 2), bty = "n")
```

